---
# The Box API requires ID values to be cast as strings
user_id:
app_user_id:
folder_id:
log_file_id:

local_fname: 'coffee_guru_log.csv'
auth_fname: 'config.json'
logging_fname: 'coffee_guru.log'
create_script: 'create_coffee_tables.sql'
insert_script: 'load_coffee_logs.sql'
db_name: 'coffee_guru.db'
slack_webhook: ''
time_zone: ''
request_timeout: 120

grind_setting_ranges:

descriptors:
    adverbs:
        - ''
    flavors:
        - ''
    balance:
        - ''

...
