name: coffee_logs
channels:
    - conda-forge
dependencies:
    - python=3.13
    - ipykernel
    - pip
    - loguru
    - numpy=2.3.4
    - pandas=2.3.3
    - pytz
    - pyyaml=6.0.3
    - requests=2.32.5
    - pip:
        - boxsdk[jwt]>=10
